### ISSUE TITLE
In the creation of table it error like Unknown database 'blogspot' 

### ISSUE THREAD

**Issue by bhattjigar** [bhattjigar/Crawling#4]
**On line 32 algo.php**
# suggestions

*_mysql does not enter like blospot.in  entery ...... *_

**Comment by JimishF** [comment]
Encode "each" content with URLencode() function

**Comment by bhattjigar** [comment]
# but i have to create database i used like

main url = blogspot.in
i convert url to 
database table name =blogspot_in

## i have only require the main domain name
